package com.heg.mapVsFlatMap;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class MapDemo {
	public static void main(String[] args) {
		
		List<String> fruits=Arrays.asList("Apple","mango","banana","kiwi","pineapple");
		
		System.out.println("List of fruit - :: " +fruits);
		
		//let use map() to convert list of fruit
		
	List list=	fruits.stream()
				.map(s -> s.length())
				.collect(Collectors.toList());
	
	System.out.println("List generated by map :: " +list);
	}
	

}
